name: my_stacked_demo
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  shared_preferences: ^0.5.10

  thrio:
    git:
      url: https://github.com/hellobike/flutter_thrio.git
      ref: main

  stacked: ^1.7.6
  stacked_hooks: ^0.1.3
  auto_route: null
  stacked_services: ^0.5.2

  get_it: null
  injectable: null
  flutter_hooks: null
  observable_ish: null

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: null
  auto_route_generator: null
  injectable_generator: null
dependency_overrides:
  analyzer: 0.39.14
flutter:
  uses-material-design: true
  fonts:
    - family: iconfont
      fonts:
        - asset: assets/icons/iconfont.ttf
